### ISSUE TITLE
Mountain Smoothing is unbounded

### ISSUE THREAD

**Issue by Hollikill** [CooperRoalson/MapGeneratorSpringPracticum#1]
Elevation goes outside the range typical of the previous generation.
Colors are configured for input `0-1`, and loop when outside that. Please fix this @kittyconfusion.
![image](https://user-images.githubusercontent.com/44882625/118826983-90872500-b881-11eb-914b-420e7e850ff5.png)
_0 smoothing passes_
![image](https://user-images.githubusercontent.com/44882625/118827065-a4cb2200-b881-11eb-9f89-fde02ac68501.png)
_1 smoothing pass_
![image](https://user-images.githubusercontent.com/44882625/118827142-b8768880-b881-11eb-9cc8-ce145a8fb7a8.png)
_15 smoothing passes_

**Comment by kittyconfusion** [comment]
It does not blend in with the green surroundings yet but I am ready to commit an initial fix to the purple.

![image](https://user-images.githubusercontent.com/65476906/118832941-aa773680-b886-11eb-8c76-251054e04778.png)
